server.port=8080

spring.application.name=payment-service
spring.datasource.url=jdbc:h2:mem:payment-service;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

comprovantes.base-url=http://localhost:8081
comprovantes.confirmacao.max-tentativas=5
comprovantes.confirmacao.intervalo-inicial-ms=500

resilience4j.circuitbreaker.instances.comprovantes.sliding-window-size=10
resilience4j.circuitbreaker.instances.comprovantes.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.comprovantes.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.comprovantes.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.comprovantes.permitted-number-of-calls-in-half-open-state=3

resilience4j.retry.instances.comprovantes.max-attempts=3
resilience4j.retry.instances.comprovantes.wait-duration=300ms

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.projetocore.payment=INFO
